"""Search over pushes: one graph search loop, with three priority rules and an optional deadlock filter.

A state is (canonical player cell, sorted box cells). The player's exact cell inside its walking
region does not change what can be pushed next, so the state keeps only the smallest cell of the
region. Successors are generated by pushing: walk the player through its region, and at each cell
next to a box, push the box if the far cell is free floor. Walking costs nothing in the search (it
is solved by BFS when the move is needed), so the search cost is measured in pushes, which is what
the solution count reports.

Priority rules, all over the same loop:
  bfs     g                 uniform cost, so the first goal popped has the fewest pushes
  greedy  h                 chases the nearest-looking goal; fast, but no optimality guarantee
  astar   g + h             optimal when h is admissible (both heuristics here are; states are reopened
                            when a cheaper path appears, which covers the matching bound's fallback)

Deadlock pruning (prune=True) drops a successor that is a deadlock (dead square or frozen box, see
deadlock.py) before it is stored. With pruning off the search still stores and expands those states
and only learns they are hopeless when they run out of moves, which is the comparison the benchmark
measures. Pruning never removes a solvable state, so the optimal push count is the same either way.

Budgets. node_budget caps expansions (states popped and expanded), and time_limit caps wall time.
A run that hits either stops with status "budget" or "time"; "exhausted" means the open list emptied,
so the level has no solution from the start (the search was complete).
"""

from __future__ import annotations

import heapq
import itertools
import time
from dataclasses import dataclass, field

from .board import LETTERS, Level, reachable, walk_path
from .deadlock import is_deadlock
from .heuristics import MATCHING, NONE, SIMPLE, h_matching, h_simple
from .tables import Tables, tables

BFS = "bfs"
GREEDY = "greedy"
ASTAR = "astar"
ALGORITHMS = (BFS, GREEDY, ASTAR)

# Default budgets. The server and the benchmark pass their own, and both stay well under the
# 1 GB of the serving machine: a stored state is a few hundred bytes.
DEFAULT_NODES = 20_000
DEFAULT_SECONDS = 10.0


@dataclass
class Result:
    """What one search run reports. `moves` is the full plan: lowercase walks, uppercase pushes."""

    algorithm: str
    heuristic: str
    prune: bool
    status: str  # "solved", "budget", "time", or "exhausted" (no solution from here)
    expanded: int = 0
    generated: int = 0
    pruned: int = 0
    seconds: float = 0.0
    h_start: int = 0
    moves: str | None = None
    samples: list[tuple[int, float]] = field(default_factory=list)  # (expanded, seconds) as the run goes

    @property
    def solved(self) -> bool:
        return self.status == "solved"

    @property
    def pushes(self) -> int | None:
        if self.moves is None:
            return None
        return sum(1 for ch in self.moves if ch.isupper())


def _heuristic_fn(t: Tables, name: str):
    if name == NONE:
        return lambda boxes: 0
    if name == SIMPLE:
        return lambda boxes: h_simple(t, boxes)
    if name == MATCHING:
        return lambda boxes: h_matching(t, boxes)
    raise ValueError(f"unknown heuristic {name!r}")


def solve(
    level: Level,
    algorithm: str = ASTAR,
    heuristic: str = MATCHING,
    prune: bool = True,
    node_budget: int = DEFAULT_NODES,
    time_limit: float | None = DEFAULT_SECONDS,
) -> Result:
    """Search from the level's starting position. Returns a Result; `moves` is set when solved."""
    if algorithm not in ALGORITHMS:
        raise ValueError(f"unknown algorithm {algorithm!r}")
    if algorithm == BFS:
        heuristic = NONE  # BFS has no heuristic; report it as such
    t = tables(level)
    h_of = _heuristic_fn(t, heuristic)
    dead = t.dead
    offs = level.offsets
    floor = level.floor
    goal_tuple = level.goals

    result = Result(algorithm=algorithm, heuristic=heuristic, prune=prune, status="exhausted")
    start_boxes = tuple(sorted(level.start_boxes))
    start_occ = set(start_boxes)
    if prune and is_deadlock(level, dead, start_occ):
        result.status = "exhausted"  # the start itself is a deadlock: no push can help
        return result
    start_player = level.start_player
    start_key = (min(reachable(level, start_player, start_occ)), start_boxes)
    result.h_start = h_of(start_boxes)

    # info[key] = (parent key, the player's cell in this state, cell of the box just pushed, direction)
    # The stored player cell is the one the search actually expanded from, so the plan can be replayed.
    info = {start_key: (None, start_player, -1, -1)}
    best_g = {start_key: 0}
    closed = set()
    hcache: dict[tuple[int, ...], int] = {}  # h depends only on the boxes, shared by every player spot

    def priority(g: int, h: int) -> tuple[int, int]:
        if algorithm == BFS:
            return (g, 0)
        if algorithm == GREEDY:
            return (h, g)
        return (g + h, h)

    counter = itertools.count()  # breaks ties so heap entries never compare keys
    h0 = hcache.setdefault(start_boxes, result.h_start)
    open_heap = [(*priority(0, h0), next(counter), start_key, 0)]
    started = time.perf_counter()
    sample_every = max(1, node_budget // 200)
    solved_key = None

    while open_heap:
        *_, key, g = heapq.heappop(open_heap)
        if key in closed or g > best_g.get(key, g):
            continue  # a stale entry: the state was expanded, or found a cheaper path later
        boxes = key[1]
        if boxes == goal_tuple:
            solved_key = key
            break
        if result.expanded >= node_budget:
            result.status = "budget"
            break
        now = time.perf_counter() - started
        if time_limit is not None and now > time_limit:
            result.status = "time"
            break
        closed.add(key)
        result.expanded += 1
        if result.expanded % sample_every == 0:
            result.samples.append((result.expanded, now))

        # Expand: the player may stand on any cell of its region, and each push starts from there.
        actual = info[key][1]
        occ = set(boxes)
        region = reachable(level, actual, occ)
        for p in region:
            for k, off in enumerate(offs):
                b = p + off
                if b not in occ:
                    continue
                nb = b + off
                if not floor[nb] or nb in occ:
                    continue
                result.generated += 1
                new_occ = (occ - {b}) | {nb}
                new_boxes = tuple(sorted(new_occ))
                if prune and is_deadlock(level, dead, new_occ):
                    result.pruned += 1
                    continue
                # The player now stands on b, where the box was. Its region gives the canonical cell.
                ckey = (min(reachable(level, b, new_occ)), new_boxes)
                ng = g + 1
                if ng >= best_g.get(ckey, ng + 1):
                    continue
                # A cheaper path to a state already expanded: reopen it. With a consistent heuristic this
                # never happens. The matching bound's Manhattan fallback can break consistency, and
                # reopening keeps A* optimal for any admissible heuristic.
                best_g[ckey] = ng
                closed.discard(ckey)
                info[ckey] = (key, b, b, k)
                h = hcache.get(new_boxes)
                if h is None:
                    h = h_of(new_boxes)
                    hcache[new_boxes] = h
                heapq.heappush(open_heap, (*priority(ng, h), next(counter), ckey, ng))

    result.seconds = time.perf_counter() - started
    if not result.samples or result.samples[-1][0] != result.expanded:
        result.samples.append((result.expanded, result.seconds))  # the last point, so every run has one
    if solved_key is not None:
        result.status = "solved"
        result.moves = _plan(level, info, solved_key)
    return result


def _plan(level: Level, info: dict, final_key) -> str:
    """Rebuild the move string from the parent links: walk to each push cell, then push."""
    chain = []
    key = final_key
    while info[key][0] is not None:
        chain.append(key)
        key = info[key][0]
    chain.reverse()
    player = level.start_player
    boxes = set(level.start_boxes)
    moves = []
    offs = level.offsets
    for key in chain:
        _, _, b, k = info[key]
        off = offs[k]
        push_cell = b - off  # the player stands behind the box to push it
        walk = walk_path(level, player, push_cell, boxes)
        if walk is None:
            raise RuntimeError("internal error: the planned push cell is unreachable")
        moves.append(walk)
        moves.append(LETTERS[k].upper())
        boxes.remove(b)
        boxes.add(b + off)
        player = b
    return "".join(moves)
